# Generated by Django 3.1.7 on 2021-03-28 21:11

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('plans', '0002_customer'),
    ]

    operations = [
        migrations.AddField(
            model_name='fitnessplan',
            name='date',
            field=models.DateField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='fitnessplan',
            name='image',
            field=models.ImageField(blank=True, upload_to='plans/images/'),
        ),
    ]
