# Generated by Django 3.1.7 on 2021-03-28 22:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('plans', '0004_fitnessplan_video'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fitnessplan',
            name='video',
            field=models.CharField(blank=True, max_length=250),
        ),
    ]
