# Generated by Django 3.1.7 on 2021-03-30 01:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('plans', '0007_auto_20210330_0127'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fitnessplan',
            name='image',
            field=models.ImageField(blank=True, upload_to='plans/images/'),
        ),
    ]
